// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ModelVer_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModelVer_1));
        
        string IMigrationMetadata.Id
        {
            get { return "202204201825418_ModelVer_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
